### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by buddhishan** [Olivescript/mycareers-issues#5] opened 2017-11-12 17:06 UTC
Forgot password reset eke mail eka enawa. Ethanin ehata wada na - Ricco

**Comment by ramithuh** [comment] 2017-11-12 18:09
the issue is.. 
http://www.mycareers.lk/**www.mycareers.lk**/password/reset/0a4c806e7412e06342c64f23bb0fa9830b33266173e1b71303c6de49907f0bf5

**Comment by sudaraka94** [comment] 2017-11-13 08:16
Hi @ramithuh and Ricco,
Thank you for reporting the bug

**Comment by sudaraka94** [comment] 2017-12-11 13:33
Fixed in v0.6

**Closed as completed by sudaraka94** 2017-12-11 13:33 UTC
Labels: bug, high
